[default]
src = 'src'
out = 'out'
libs = ['lib']
libraries = ['src/libraries/FreemoonDEXLibrary.sol:FreemoonDEXLibrary:0x9fe46736679d2d9a65f0992f2272de9f3c7fa6e0']

# See more config options https://github.com/foundry-rs/foundry/tree/master/config