[default]
src = 'src'
out = 'out'
libs = ['lib']
# libraries = ['src/libraries/FreemoonDEXLibrary.sol:FreemoonDEXLibrary:']

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
